<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Techer.Aws.Shared\Techer.Aws.Shared.csproj" />
    <ProjectReference Include="..\Techer.Common.Domain\Techer.Common.Domain.csproj" />
    <ProjectReference Include="..\Techer.Common.Extensions\Techer.Common.Extensions.csproj" />
  </ItemGroup>

  <ItemGroup>
	<PackageReference Include="AWSSDK.SQS" Version="3.7.2.113" />
  </ItemGroup>

</Project>
