<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Arauco.Otimizador.Data.Entities\Arauco.Otimizador.Data.Entities.csproj" />
    <ProjectReference Include="..\Techer.Aws.Secrets\Techer.Aws.Secrets.csproj" />
    <ProjectReference Include="..\Techer.Data.MySql\Techer.Data.MySql.csproj" />
  </ItemGroup>

</Project>
