AWSTemplateFormatVersion: 2010-09-09
Description: >-
  arauco-otimizador-data-source

Transform:
- AWS::Serverless-2016-10-31

Parameters:
  ENV:
    Description: Required. Environment dev/test/prod
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - test
      - prod

Mappings:
  dev:
    values:
      AspNetEnv: Development

  test:
    values:
      AspNetEnv: Testing

  prod:
    values:
      AspNetEnv: Production

Globals:
  Function:
    VpcConfig:
      SecurityGroupIds:
        - !ImportValue stack-setup-AppSecurityGroup
      SubnetIds:
        - !ImportValue stack-setup-PrivateSubnet0
        - !ImportValue stack-setup-PrivateSubnet1
        - !ImportValue stack-setup-PrivateSubnet2
    Environment:
      Variables:
        ASPNETCORE_ENVIRONMENT: !FindInMap [ !Ref ENV, values, AspNetEnv ]

Resources:
  DataSourceBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub
        - 'arauco-otimizador-data-source-${Env}'
        - Env: !Ref ENV
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldFiles
            Status: Enabled
            ExpirationInDays: 7
            NoncurrentVersionExpirationInDays: 7

  DataSourceFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: data-source
      Description: Geracao das fontes de dados para QlikSense
      Handler: Arauco.Otimizador.Function.DataSource::Arauco.Otimizador.Function.DataSource.Function::FunctionHandler
      MemorySize: 2048
      Timeout: 600
      Runtime: dotnet10
      Events:
        ScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: 'cron(0 0 * * ? *)'
            Name: DataSourceRate
            Description: Schedule
            Enabled: true
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy: 
            SecretArn: arn:aws:secretsmanager:sa-east-1:*:secret:*
        - DynamoDBCrudPolicy:
            TableName: KeyValue
        - S3CrudPolicy:
            BucketName: !Ref DataSourceBucket
