AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >-
  Arauco.Otimizador.Function.Florestal

  Sample SAM Template for Arauco.Otimizador.Function.Florestal

Resources:
  FlorestalFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: otimizador-florestal
      Description: Lambda function to process CSV files for Florestal.
      Handler: Arauco.Otimizador.Function.Florestal::Arauco.Otimizador.Function.Florestal.Function::FunctionHandler
      MemorySize: 1024
      Timeout: 45
      Runtime: dotnet10
      Architectures:
        - x86_64
      Environment:
        Variables:
          SENDER_EMAIL: "Inteligência de Dados Florestal <inteligenciadedadosflorestal@techer.com.br>" # Replace with your sender email
          RECIPIENT_EMAILS: "informe.kpim@arauco.com,ext.luciano.motti@arauco.com" # Replace with your recipient emails
      FunctionUrlConfig:
        AuthType: NONE
        Cors:
          AllowOrigins:
            - "*"
          AllowMethods:
            - POST
          AllowHeaders:
            - "Content-Type"
          MaxAge: 86400
      Policies:
        - Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource: "*"
        - Statement:
          - Effect: Allow
            Action:
              - ses:SendEmail
            Resource: "*"


