<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.18" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Arauco.Otimizador.Data.MySql\Arauco.Otimizador.Data.MySql.csproj" />
    <ProjectReference Include="..\Arauco.Otimizador.Service.CartaoService\Arauco.Otimizador.Service.CartaoService.csproj" />
    <ProjectReference Include="..\Arauco.Otimizador.Service.CenarioService\Arauco.Otimizador.Service.CenarioService.csproj" />
    <ProjectReference Include="..\Arauco.Otimizador.Service.ContaService\Arauco.Otimizador.Service.ContaService.csproj" />
    <ProjectReference Include="..\Arauco.Otimizador.Service.DemandaService\Arauco.Otimizador.Service.DemandaService.csproj" />
    <ProjectReference Include="..\Arauco.Otimizador.Service.OtimizadorService\Arauco.Otimizador.Service.OtimizadorService.csproj" />
    <ProjectReference Include="..\Arauco.Otimizador.WebApi.Base\Arauco.Otimizador.WebApi.Base.csproj" />
  </ItemGroup>

</Project>