<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="obj\Debug\net10.0\.NETCoreApp,Version=v10.0.AssemblyAttributes.cs" />
    <Compile Include="obj\Debug\net10.0\Arauco.Otimizador.WebApi.AssemblyInfo.cs" />
    <Compile Include="obj\Debug\net10.0\Arauco.Otimizador.WebApi.GlobalUsings.g.cs" />
    <Compile Include="obj\Debug\net10.0\Arauco.Otimizador.WebApi.MvcApplicationPartsAssemblyInfo.cs" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="bin\Debug\net10.0\appsettings.Development.json" />
    <Content Include="bin\Debug\net10.0\appsettings.json" />
    <Content Include="bin\Debug\net10.0\Arauco.Otimizador.WebApi.deps.json" />
    <Content Include="bin\Debug\net10.0\Arauco.Otimizador.WebApi.runtimeconfig.json" />
    <Content Include="bin\Debug\net10.0\Arauco.Otimizador.WebApi.staticwebassets.endpoints.json" />
    <Content Include="obj\Arauco.Otimizador.WebApi.csproj.nuget.dgspec.json" />
    <Content Include="obj\Debug\net10.0\ApiEndpoints.json" />
    <Content Include="obj\Debug\net10.0\Arauco.Otimizador.WebApi.csproj.FileListAbsolute.txt" />
    <Content Include="obj\Debug\net10.0\rjsmcshtml.dswa.cache.json" />
    <Content Include="obj\Debug\net10.0\rjsmrazor.dswa.cache.json" />
    <Content Include="obj\Debug\net10.0\rpswa.dswa.cache.json" />
    <Content Include="obj\Debug\net10.0\staticwebassets.build.endpoints.json" />
    <Content Include="obj\Debug\net10.0\staticwebassets.build.json" />
    <Content Include="obj\Debug\net10.0\staticwebassets.references.upToDateCheck.txt" />
    <Content Include="obj\Debug\net10.0\staticwebassets.removed.txt" />
    <Content Include="obj\project.assets.json" />
  </ItemGroup>

  <ItemGroup>
    <None Include="bin\Debug\net10.0\Amazon.Lambda.APIGatewayEvents.dll" />
    <None Include="bin\Debug\net10.0\Amazon.Lambda.ApplicationLoadBalancerEvents.dll" />
    <None Include="bin\Debug\net10.0\Amazon.Lambda.AspNetCoreServer.dll" />
    <None Include="bin\Debug\net10.0\Amazon.Lambda.Core.dll" />
    <None Include="bin\Debug\net10.0\Amazon.Lambda.Logging.AspNetCore.dll" />
    <None Include="bin\Debug\net10.0\Amazon.Lambda.Serialization.SystemTextJson.dll" />
    <None Include="bin\Debug\net10.0\Arauco.Otimizador.Aws.Shared.dll" />
    <None Include="bin\Debug\net10.0\Arauco.Otimizador.Aws.Shared.pdb" />
    <None Include="bin\Debug\net10.0\Arauco.Otimizador.Common.Domain.dll" />
    <None Include="bin\Debug\net10.0\Arauco.Otimizador.Common.Domain.pdb" />
    <None Include="bin\Debug\net10.0\Arauco.Otimizador.Common.Storage.dll" />
    <None Include="bin\Debug\net10.0\Arauco.Otimizador.Common.Storage.pdb" />
    <None Include="bin\Debug\net10.0\Arauco.Otimizador.Data.Dynamo.dll" />
    <None Include="bin\Debug\net10.0\Arauco.Otimizador.Data.Dynamo.pdb" />
    <None Include="bin\Debug\net10.0\Arauco.Otimizador.Data.Entities.dll" />
    <None Include="bin\Debug\net10.0\Arauco.Otimizador.Data.Entities.pdb" />
    <None Include="bin\Debug\net10.0\Arauco.Otimizador.Data.MySql.dll" />
    <None Include="bin\Debug\net10.0\Arauco.Otimizador.Data.MySql.pdb" />
    <None Include="bin\Debug\net10.0\Arauco.Otimizador.Service.Base.dll" />
    <None Include="bin\Debug\net10.0\Arauco.Otimizador.Service.Base.pdb" />
    <None Include="bin\Debug\net10.0\Arauco.Otimizador.Service.CartaoService.dll" />
    <None Include="bin\Debug\net10.0\Arauco.Otimizador.Service.CartaoService.pdb" />
    <None Include="bin\Debug\net10.0\Arauco.Otimizador.Service.CenarioService.dll" />
    <None Include="bin\Debug\net10.0\Arauco.Otimizador.Service.CenarioService.pdb" />
    <None Include="bin\Debug\net10.0\Arauco.Otimizador.Service.DemandaService.dll" />
    <None Include="bin\Debug\net10.0\Arauco.Otimizador.Service.DemandaService.pdb" />
    <None Include="bin\Debug\net10.0\Arauco.Otimizador.Service.ParametroService.dll" />
    <None Include="bin\Debug\net10.0\Arauco.Otimizador.Service.ParametroService.pdb" />
    <None Include="bin\Debug\net10.0\Arauco.Otimizador.WebApi.Base.dll" />
    <None Include="bin\Debug\net10.0\Arauco.Otimizador.WebApi.Base.pdb" />
    <None Include="bin\Debug\net10.0\Arauco.Otimizador.WebApi.dll" />
    <None Include="bin\Debug\net10.0\Arauco.Otimizador.WebApi.exe" />
    <None Include="bin\Debug\net10.0\Arauco.Otimizador.WebApi.pdb" />
    <None Include="bin\Debug\net10.0\AWSSDK.CognitoIdentityProvider.dll" />
    <None Include="bin\Debug\net10.0\AWSSDK.Core.dll" />
    <None Include="bin\Debug\net10.0\AWSSDK.DynamoDBv2.dll" />
    <None Include="bin\Debug\net10.0\AWSSDK.SecretsManager.dll" />
    <None Include="bin\Debug\net10.0\Microsoft.AspNetCore.Authentication.JwtBearer.dll" />
    <None Include="bin\Debug\net10.0\Microsoft.AspNetCore.JsonPatch.dll" />
    <None Include="bin\Debug\net10.0\Microsoft.AspNetCore.Mvc.NewtonsoftJson.dll" />
    <None Include="bin\Debug\net10.0\Microsoft.AspNetCore.OpenApi.dll" />
    <None Include="bin\Debug\net10.0\Microsoft.Bcl.Cryptography.dll" />
    <None Include="bin\Debug\net10.0\Microsoft.EntityFrameworkCore.Abstractions.dll" />
    <None Include="bin\Debug\net10.0\Microsoft.EntityFrameworkCore.dll" />
    <None Include="bin\Debug\net10.0\Microsoft.EntityFrameworkCore.Relational.dll" />
    <None Include="bin\Debug\net10.0\Microsoft.IdentityModel.Abstractions.dll" />
    <None Include="bin\Debug\net10.0\Microsoft.IdentityModel.JsonWebTokens.dll" />
    <None Include="bin\Debug\net10.0\Microsoft.IdentityModel.Logging.dll" />
    <None Include="bin\Debug\net10.0\Microsoft.IdentityModel.Protocols.dll" />
    <None Include="bin\Debug\net10.0\Microsoft.IdentityModel.Protocols.OpenIdConnect.dll" />
    <None Include="bin\Debug\net10.0\Microsoft.IdentityModel.Tokens.dll" />
    <None Include="bin\Debug\net10.0\Microsoft.OpenApi.dll" />
    <None Include="bin\Debug\net10.0\MySqlConnector.dll" />
    <None Include="bin\Debug\net10.0\Nanoid.dll" />
    <None Include="bin\Debug\net10.0\Newtonsoft.Json.Bson.dll" />
    <None Include="bin\Debug\net10.0\Newtonsoft.Json.dll" />
    <None Include="bin\Debug\net10.0\Polly.Core.dll" />
    <None Include="bin\Debug\net10.0\Polly.dll" />
    <None Include="bin\Debug\net10.0\Pomelo.EntityFrameworkCore.MySql.dll" />
    <None Include="bin\Debug\net10.0\System.IdentityModel.Tokens.Jwt.dll" />
    <None Include="bin\Debug\net10.0\System.Linq.Dynamic.Core.dll" />
    <None Include="bin\Debug\net10.0\Techer.Aws.Cognito.dll" />
    <None Include="bin\Debug\net10.0\Techer.Aws.Cognito.pdb" />
    <None Include="bin\Debug\net10.0\Techer.Aws.Dynamo.dll" />
    <None Include="bin\Debug\net10.0\Techer.Aws.Dynamo.pdb" />
    <None Include="bin\Debug\net10.0\Techer.Aws.Secrets.dll" />
    <None Include="bin\Debug\net10.0\Techer.Aws.Secrets.pdb" />
    <None Include="bin\Debug\net10.0\Techer.Aws.Shared.dll" />
    <None Include="bin\Debug\net10.0\Techer.Aws.Shared.pdb" />
    <None Include="bin\Debug\net10.0\Techer.Common.Domain.dll" />
    <None Include="bin\Debug\net10.0\Techer.Common.Domain.pdb" />
    <None Include="bin\Debug\net10.0\Techer.Common.Extensions.dll" />
    <None Include="bin\Debug\net10.0\Techer.Common.Extensions.pdb" />
    <None Include="bin\Debug\net10.0\Techer.Common.Id.dll" />
    <None Include="bin\Debug\net10.0\Techer.Common.Id.pdb" />
    <None Include="bin\Debug\net10.0\Techer.Common.Json.dll" />
    <None Include="bin\Debug\net10.0\Techer.Common.Json.pdb" />
    <None Include="bin\Debug\net10.0\Techer.Common.WebApi.dll" />
    <None Include="bin\Debug\net10.0\Techer.Common.WebApi.pdb" />
    <None Include="bin\Debug\net10.0\Techer.Data.MySql.dll" />
    <None Include="bin\Debug\net10.0\Techer.Data.MySql.pdb" />
    <None Include="bin\Debug\net10.0\Ulid.dll" />
    <None Include="obj\Arauco.Otimizador.WebApi.csproj.nuget.g.props" />
    <None Include="obj\Arauco.Otimizador.WebApi.csproj.nuget.g.targets" />
    <None Include="obj\Debug\net10.0\apphost.exe" />
    <None Include="obj\Debug\net10.0\Arauco.O.77440F16.Up2Date" />
    <None Include="obj\Debug\net10.0\Arauco.Otimizador.WebApi.AssemblyInfoInputs.cache" />
    <None Include="obj\Debug\net10.0\Arauco.Otimizador.WebApi.assets.cache" />
    <None Include="obj\Debug\net10.0\Arauco.Otimizador.WebApi.csproj.AssemblyReference.cache" />
    <None Include="obj\Debug\net10.0\Arauco.Otimizador.WebApi.csproj.CoreCompileInputs.cache" />
    <None Include="obj\Debug\net10.0\Arauco.Otimizador.WebApi.dll" />
    <None Include="obj\Debug\net10.0\Arauco.Otimizador.WebApi.GeneratedMSBuildEditorConfig.editorconfig" />
    <None Include="obj\Debug\net10.0\Arauco.Otimizador.WebApi.genruntimeconfig.cache" />
    <None Include="obj\Debug\net10.0\Arauco.Otimizador.WebApi.MvcApplicationPartsAssemblyInfo.cache" />
    <None Include="obj\Debug\net10.0\Arauco.Otimizador.WebApi.pdb" />
    <None Include="obj\Debug\net10.0\refint\Arauco.Otimizador.WebApi.dll" />
    <None Include="obj\Debug\net10.0\ref\Arauco.Otimizador.WebApi.dll" />
    <None Include="obj\Debug\net10.0\staticwebassets.build.json.cache" />
    <None Include="obj\Debug\net10.0\swae.build.ex.cache" />
    <None Include="obj\project.nuget.cache" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Arauco.Otimizador.Data.MySql\Arauco.Otimizador.Data.MySql.csproj" />
    <ProjectReference Include="..\Arauco.Otimizador.Service.CartaoService\Arauco.Otimizador.Service.CartaoService.csproj" />
    <ProjectReference Include="..\Arauco.Otimizador.Service.CenarioService\Arauco.Otimizador.Service.CenarioService.csproj" />
    <ProjectReference Include="..\Arauco.Otimizador.Service.DemandaService\Arauco.Otimizador.Service.DemandaService.csproj" />
    <ProjectReference Include="..\Arauco.Otimizador.Service.ParametroService\Arauco.Otimizador.Service.ParametroService.csproj" />
    <ProjectReference Include="..\Arauco.Otimizador.WebApi.Base\Arauco.Otimizador.WebApi.Base.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="obj\Debug\net10.0\staticwebassets\" />
  </ItemGroup>

</Project>
