AWSTemplateFormatVersion: 2010-09-09
Description: >-
  arauco-otimizador-flow-api

Transform:
- AWS::Serverless-2016-10-31

Parameters:
  ENV:
    Description: Required. Environment dev/test/prod
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - test
      - prod
  APIDOMAIN:
    Description: Required. Domain name for API
    Type: String
    
Mappings:
  dev:
    values:
      AspNetEnv: Development
  test:
    values:
      AspNetEnv: Testing
  prod:
    values:
      AspNetEnv: Production

Globals:
  Function:
    Environment:
      Variables:
        ASPNETCORE_ENVIRONMENT: !FindInMap [ !Ref ENV, values, AspNetEnv ]

  Api:
    EndpointConfiguration: REGIONAL
    Cors:
      AllowHeaders: "'Content-Type,x-workspace,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      AllowMethods: "'DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT'"
      AllowOrigin: "'*'"

Resources:
  FlowApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: flow-api
      StageName: Staging

  FlowApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: flow-api
      Description: Flow API
      Handler: Arauco.Otimizador.WebApi.Flow::Arauco.Otimizador.WebApi.Flow.LambdaEntryPoint::FunctionHandlerAsync
      MemorySize: 1024
      Timeout: 60
      Runtime: dotnet10
      Events:
        FlowApiProxy:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId: !Ref FlowApi
      Policies:
        - DynamoDBCrudPolicy:
            TableName: Flow
        - DynamoDBCrudPolicy:
            TableName: KeyValue

  UrlMapping:
    Type: AWS::ApiGateway::BasePathMapping
    DependsOn: 
      - FlowApi
      - FlowApiFunction
    Properties:
      BasePath: flow
      DomainName: !Ref APIDOMAIN
      RestApiId: !Ref FlowApi
      Stage: !Ref FlowApi.Stage
