<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Scripts\Script004 - Insert Centro.sql" />
    <None Remove="Scripts\Script005 - Insert Produto.sql" />
    <None Remove="Scripts\Script006 - Insert Elegibilidade.sql" />
    <None Remove="Scripts\Script007 - Insert Capacidade.sql" />
    <None Remove="Scripts\Script008 - Alteracao Tamanho Id Pedido Otimizado.sql" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Scripts\Script001 - Otimizador.sql" />
    <EmbeddedResource Include="Scripts\Script002 - OtimizacaoResultado.sql" />
    <EmbeddedResource Include="Scripts\Script003 - Datasets.sql" />
    <EmbeddedResource Include="Scripts\Script004 - Insert Centro.sql" />
    <EmbeddedResource Include="Scripts\Script005 - Insert Produto.sql" />
    <EmbeddedResource Include="Scripts\Script006 - Insert Elegibilidade.sql" />
    <EmbeddedResource Include="Scripts\Script007 - Insert Capacidade.sql" />
    <EmbeddedResource Include="Scripts\Script009 - Alteracao Tamanho Id Pedido.sql" />
    <EmbeddedResource Include="Scripts\Script008 - Alteracao Tamanho Id Pedido Otimizado.sql" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="dbup-mysql" Version="6.1.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.18" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Arauco.Otimizador.Data.MySql\Arauco.Otimizador.Data.MySql.csproj" />
  </ItemGroup>

</Project>