<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Scripts\Script001 - Otimizador.sql" />
    <EmbeddedResource Include="Scripts\Script003 - Criterios.sql" />
    <EmbeddedResource Include="Scripts\Script004 - OtimizacaoResultado.sql" />
    <EmbeddedResource Include="Scripts\Script005 - OtimizacaoV2.sql" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="dbup-mysql" Version="6.1.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.18" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Arauco.Otimizador.Data.MySql\Arauco.Otimizador.Data.MySql.csproj" />
  </ItemGroup>

</Project>