<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
	<ProjectReference Include="..\Arauco.Otimizador.Common.Domain\Arauco.Otimizador.Common.Domain.csproj" />
	<ProjectReference Include="..\Techer.Common.Extensions\Techer.Common.Extensions.csproj" />
	<ProjectReference Include="..\Techer.Common.Id\Techer.Common.Id.csproj" />
  </ItemGroup>

</Project>
