<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="FluentValidation" Version="11.8.0" />
	<PackageReference Include="libphonenumber-csharp" Version="8.13.24" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Techer.Common.Domain\Techer.Common.Domain.csproj" />
    <ProjectReference Include="..\Techer.Common.Extensions\Techer.Common.Extensions.csproj" />
  </ItemGroup>

</Project>
