AWSTemplateFormatVersion: 2010-09-09
Description: >-
  arauco-otimizador-data-api

Transform:
- AWS::Serverless-2016-10-31

Parameters:
  ENV:
    Description: Required. Environment dev/test/prod
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - test
      - prod
  APIDOMAIN:
    Description: Required. Domain name for API
    Type: String
    
Mappings:
  dev:
    values:
      AspNetEnv: Development
  test:
    values:
      AspNetEnv: Testing
  prod:
    values:
      AspNetEnv: Production

Globals:
  Function:
    VpcConfig:
      SecurityGroupIds:
        - !ImportValue stack-setup-AppSecurityGroup
      SubnetIds:
        - !ImportValue stack-setup-PrivateSubnet0
        - !ImportValue stack-setup-PrivateSubnet1
        - !ImportValue stack-setup-PrivateSubnet2
    Environment:
      Variables:
        ASPNETCORE_ENVIRONMENT: !FindInMap [ !Ref ENV, values, AspNetEnv ]

  Api:
    EndpointConfiguration: REGIONAL
    Cors:
      AllowHeaders: "'Content-Type,x-workspace,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      AllowMethods: "'DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT'"
      AllowOrigin: "'*'"

Resources:
  DataApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: data-api
      StageName: Staging

  DataApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: data-api
      Description: Data API
      Handler: Arauco.Otimizador.WebApi.DataApi::Arauco.Otimizador.WebApi.DataApi.LambdaEntryPoint::FunctionHandlerAsync
      MemorySize: 2048
      Timeout: 60
      Runtime: dotnet10
      Events:
        DataApiProxy:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId: !Ref DataApi
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy: 
            SecretArn: arn:aws:secretsmanager:sa-east-1:*:secret:*
        - DynamoDBCrudPolicy:
            TableName: KeyValue
        - DynamoDBCrudPolicy:
            TableName: Log

  UrlMapping:
    Type: AWS::ApiGateway::BasePathMapping
    DependsOn: 
      - DataApi
      - DataApiFunction
    Properties:
      BasePath: data
      DomainName: !Ref APIDOMAIN
      RestApiId: !Ref DataApi
      Stage: !Ref DataApi.Stage
