//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WsSenior
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.senior.com.br", ConfigurationName="WsSenior.rubi_Syncbr_com_arauco_rh_dadosColaborador")]
    public interface rubi_Syncbr_com_arauco_rh_dadosColaborador
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.senior.com.br/rubi_Syncbr_com_arauco_rh_dadosColaborador/get_dado" +
            "s_colaboradorRequest", ReplyAction="http://services.senior.com.br/rubi_Syncbr_com_arauco_rh_dadosColaborador/get_dado" +
            "s_colaboradorResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        System.Threading.Tasks.Task<WsSenior.dadosColaboradorgetdadoscolaboradorOut> get_dados_colaboradorAsync(string user, string password, int encryption, WsSenior.dadosColaboradorgetdadoscolaboradorIn parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.senior.com.br/rubi_Syncbr_com_arauco_rh_dadosColaborador/get_dado" +
            "s_colaborador_BKPRequest", ReplyAction="http://services.senior.com.br/rubi_Syncbr_com_arauco_rh_dadosColaborador/get_dado" +
            "s_colaborador_BKPResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        System.Threading.Tasks.Task<WsSenior.dadosColaboradorgetdadoscolaboradorBKPOut> get_dados_colaborador_BKPAsync(string user, string password, int encryption, WsSenior.dadosColaboradorgetdadoscolaboradorBKPIn parameters);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.senior.com.br")]
    public partial class dadosColaboradorgetdadoscolaboradorIn
    {
        
        private string codFilField;
        
        private string flowInstanceIDField;
        
        private string flowNameField;
        
        private string numCadField;
        
        private string numEmpField;
        
        private string tipColField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string codFil
        {
            get
            {
                return this.codFilField;
            }
            set
            {
                this.codFilField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string flowInstanceID
        {
            get
            {
                return this.flowInstanceIDField;
            }
            set
            {
                this.flowInstanceIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string flowName
        {
            get
            {
                return this.flowNameField;
            }
            set
            {
                this.flowNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string numCad
        {
            get
            {
                return this.numCadField;
            }
            set
            {
                this.numCadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string numEmp
        {
            get
            {
                return this.numEmpField;
            }
            set
            {
                this.numEmpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public string tipCol
        {
            get
            {
                return this.tipColField;
            }
            set
            {
                this.tipColField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.senior.com.br")]
    public partial class dadosColaboradorgetdadoscolaboradorBKPOutDados
    {
        
        private string codCcuField;
        
        private System.Nullable<int> codFilRetField;
        
        private bool codFilRetFieldSpecified;
        
        private string datNasField;
        
        private string desFilField;
        
        private string desPosField;
        
        private string feriasField;
        
        private string genColField;
        
        private System.Nullable<int> matGesField;
        
        private bool matGesFieldSpecified;
        
        private string nomFunField;
        
        private System.Nullable<int> numCadRetField;
        
        private bool numCadRetFieldSpecified;
        
        private string numCelField;
        
        private System.Nullable<double> numCraField;
        
        private bool numCraFieldSpecified;
        
        private System.Nullable<int> numEmpRetField;
        
        private bool numEmpRetFieldSpecified;
        
        private string posTraField;
        
        private string statusField;
        
        private System.Nullable<int> tipColField;
        
        private bool tipColFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string codCcu
        {
            get
            {
                return this.codCcuField;
            }
            set
            {
                this.codCcuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public System.Nullable<int> codFilRet
        {
            get
            {
                return this.codFilRetField;
            }
            set
            {
                this.codFilRetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codFilRetSpecified
        {
            get
            {
                return this.codFilRetFieldSpecified;
            }
            set
            {
                this.codFilRetFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string datNas
        {
            get
            {
                return this.datNasField;
            }
            set
            {
                this.datNasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string desFil
        {
            get
            {
                return this.desFilField;
            }
            set
            {
                this.desFilField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string desPos
        {
            get
            {
                return this.desPosField;
            }
            set
            {
                this.desPosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public string ferias
        {
            get
            {
                return this.feriasField;
            }
            set
            {
                this.feriasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public string genCol
        {
            get
            {
                return this.genColField;
            }
            set
            {
                this.genColField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=7)]
        public System.Nullable<int> matGes
        {
            get
            {
                return this.matGesField;
            }
            set
            {
                this.matGesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool matGesSpecified
        {
            get
            {
                return this.matGesFieldSpecified;
            }
            set
            {
                this.matGesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=8)]
        public string nomFun
        {
            get
            {
                return this.nomFunField;
            }
            set
            {
                this.nomFunField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=9)]
        public System.Nullable<int> numCadRet
        {
            get
            {
                return this.numCadRetField;
            }
            set
            {
                this.numCadRetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numCadRetSpecified
        {
            get
            {
                return this.numCadRetFieldSpecified;
            }
            set
            {
                this.numCadRetFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=10)]
        public string numCel
        {
            get
            {
                return this.numCelField;
            }
            set
            {
                this.numCelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=11)]
        public System.Nullable<double> numCra
        {
            get
            {
                return this.numCraField;
            }
            set
            {
                this.numCraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numCraSpecified
        {
            get
            {
                return this.numCraFieldSpecified;
            }
            set
            {
                this.numCraFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=12)]
        public System.Nullable<int> numEmpRet
        {
            get
            {
                return this.numEmpRetField;
            }
            set
            {
                this.numEmpRetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numEmpRetSpecified
        {
            get
            {
                return this.numEmpRetFieldSpecified;
            }
            set
            {
                this.numEmpRetFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=13)]
        public string posTra
        {
            get
            {
                return this.posTraField;
            }
            set
            {
                this.posTraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=14)]
        public string status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=15)]
        public System.Nullable<int> tipCol
        {
            get
            {
                return this.tipColField;
            }
            set
            {
                this.tipColField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipColSpecified
        {
            get
            {
                return this.tipColFieldSpecified;
            }
            set
            {
                this.tipColFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.senior.com.br")]
    public partial class dadosColaboradorgetdadoscolaboradorBKPOut
    {
        
        private dadosColaboradorgetdadoscolaboradorBKPOutDados[] dadosField;
        
        private string erroExecucaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dados", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public dadosColaboradorgetdadoscolaboradorBKPOutDados[] dados
        {
            get
            {
                return this.dadosField;
            }
            set
            {
                this.dadosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string erroExecucao
        {
            get
            {
                return this.erroExecucaoField;
            }
            set
            {
                this.erroExecucaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.senior.com.br")]
    public partial class dadosColaboradorgetdadoscolaboradorBKPIn
    {
        
        private System.Nullable<int> codFilField;
        
        private bool codFilFieldSpecified;
        
        private string flowInstanceIDField;
        
        private string flowNameField;
        
        private System.Nullable<int> numCadField;
        
        private bool numCadFieldSpecified;
        
        private System.Nullable<int> numEmpField;
        
        private bool numEmpFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public System.Nullable<int> codFil
        {
            get
            {
                return this.codFilField;
            }
            set
            {
                this.codFilField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codFilSpecified
        {
            get
            {
                return this.codFilFieldSpecified;
            }
            set
            {
                this.codFilFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string flowInstanceID
        {
            get
            {
                return this.flowInstanceIDField;
            }
            set
            {
                this.flowInstanceIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string flowName
        {
            get
            {
                return this.flowNameField;
            }
            set
            {
                this.flowNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public System.Nullable<int> numCad
        {
            get
            {
                return this.numCadField;
            }
            set
            {
                this.numCadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numCadSpecified
        {
            get
            {
                return this.numCadFieldSpecified;
            }
            set
            {
                this.numCadFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public System.Nullable<int> numEmp
        {
            get
            {
                return this.numEmpField;
            }
            set
            {
                this.numEmpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numEmpSpecified
        {
            get
            {
                return this.numEmpFieldSpecified;
            }
            set
            {
                this.numEmpFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.senior.com.br")]
    public partial class dadosColaboradorgetdadoscolaboradorOutDados
    {
        
        private string codCcuField;
        
        private System.Nullable<int> codFilRetField;
        
        private bool codFilRetFieldSpecified;
        
        private string codigo_cargoField;
        
        private string cpfField;
        
        private string dDD2Field;
        
        private string datNasField;
        
        private string ddd1Field;
        
        private string desFilField;
        
        private string desPosField;
        
        private string descricao_cargoField;
        
        private string email_comercialField;
        
        private string email_particularField;
        
        private string feriasField;
        
        private string genColField;
        
        private System.Nullable<int> matGesField;
        
        private bool matGesFieldSpecified;
        
        private string nomFunField;
        
        private System.Nullable<int> numCadRetField;
        
        private bool numCadRetFieldSpecified;
        
        private string numCelField;
        
        private System.Nullable<double> numCraField;
        
        private bool numCraFieldSpecified;
        
        private System.Nullable<int> numEmpRetField;
        
        private bool numEmpRetFieldSpecified;
        
        private string posTraField;
        
        private string statusField;
        
        private string telefone_2Field;
        
        private System.Nullable<int> tipColField;
        
        private bool tipColFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string codCcu
        {
            get
            {
                return this.codCcuField;
            }
            set
            {
                this.codCcuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public System.Nullable<int> codFilRet
        {
            get
            {
                return this.codFilRetField;
            }
            set
            {
                this.codFilRetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codFilRetSpecified
        {
            get
            {
                return this.codFilRetFieldSpecified;
            }
            set
            {
                this.codFilRetFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string codigo_cargo
        {
            get
            {
                return this.codigo_cargoField;
            }
            set
            {
                this.codigo_cargoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string cpf
        {
            get
            {
                return this.cpfField;
            }
            set
            {
                this.cpfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string DDD2
        {
            get
            {
                return this.dDD2Field;
            }
            set
            {
                this.dDD2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public string datNas
        {
            get
            {
                return this.datNasField;
            }
            set
            {
                this.datNasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public string ddd1
        {
            get
            {
                return this.ddd1Field;
            }
            set
            {
                this.ddd1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=7)]
        public string desFil
        {
            get
            {
                return this.desFilField;
            }
            set
            {
                this.desFilField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=8)]
        public string desPos
        {
            get
            {
                return this.desPosField;
            }
            set
            {
                this.desPosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=9)]
        public string descricao_cargo
        {
            get
            {
                return this.descricao_cargoField;
            }
            set
            {
                this.descricao_cargoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=10)]
        public string email_comercial
        {
            get
            {
                return this.email_comercialField;
            }
            set
            {
                this.email_comercialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=11)]
        public string email_particular
        {
            get
            {
                return this.email_particularField;
            }
            set
            {
                this.email_particularField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=12)]
        public string ferias
        {
            get
            {
                return this.feriasField;
            }
            set
            {
                this.feriasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=13)]
        public string genCol
        {
            get
            {
                return this.genColField;
            }
            set
            {
                this.genColField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=14)]
        public System.Nullable<int> matGes
        {
            get
            {
                return this.matGesField;
            }
            set
            {
                this.matGesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool matGesSpecified
        {
            get
            {
                return this.matGesFieldSpecified;
            }
            set
            {
                this.matGesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=15)]
        public string nomFun
        {
            get
            {
                return this.nomFunField;
            }
            set
            {
                this.nomFunField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=16)]
        public System.Nullable<int> numCadRet
        {
            get
            {
                return this.numCadRetField;
            }
            set
            {
                this.numCadRetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numCadRetSpecified
        {
            get
            {
                return this.numCadRetFieldSpecified;
            }
            set
            {
                this.numCadRetFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=17)]
        public string numCel
        {
            get
            {
                return this.numCelField;
            }
            set
            {
                this.numCelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=18)]
        public System.Nullable<double> numCra
        {
            get
            {
                return this.numCraField;
            }
            set
            {
                this.numCraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numCraSpecified
        {
            get
            {
                return this.numCraFieldSpecified;
            }
            set
            {
                this.numCraFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=19)]
        public System.Nullable<int> numEmpRet
        {
            get
            {
                return this.numEmpRetField;
            }
            set
            {
                this.numEmpRetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numEmpRetSpecified
        {
            get
            {
                return this.numEmpRetFieldSpecified;
            }
            set
            {
                this.numEmpRetFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=20)]
        public string posTra
        {
            get
            {
                return this.posTraField;
            }
            set
            {
                this.posTraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=21)]
        public string status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=22)]
        public string telefone_2
        {
            get
            {
                return this.telefone_2Field;
            }
            set
            {
                this.telefone_2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=23)]
        public System.Nullable<int> tipCol
        {
            get
            {
                return this.tipColField;
            }
            set
            {
                this.tipColField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipColSpecified
        {
            get
            {
                return this.tipColFieldSpecified;
            }
            set
            {
                this.tipColFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.senior.com.br")]
    public partial class dadosColaboradorgetdadoscolaboradorOut
    {
        
        private dadosColaboradorgetdadoscolaboradorOutDados[] dadosField;
        
        private string erroExecucaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dados", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public dadosColaboradorgetdadoscolaboradorOutDados[] dados
        {
            get
            {
                return this.dadosField;
            }
            set
            {
                this.dadosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string erroExecucao
        {
            get
            {
                return this.erroExecucaoField;
            }
            set
            {
                this.erroExecucaoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface rubi_Syncbr_com_arauco_rh_dadosColaboradorChannel : WsSenior.rubi_Syncbr_com_arauco_rh_dadosColaborador, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class rubi_Syncbr_com_arauco_rh_dadosColaboradorClient : System.ServiceModel.ClientBase<WsSenior.rubi_Syncbr_com_arauco_rh_dadosColaborador>, WsSenior.rubi_Syncbr_com_arauco_rh_dadosColaborador
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public rubi_Syncbr_com_arauco_rh_dadosColaboradorClient() : 
                base(rubi_Syncbr_com_arauco_rh_dadosColaboradorClient.GetDefaultBinding(), rubi_Syncbr_com_arauco_rh_dadosColaboradorClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.rubi_Syncbr_com_arauco_rh_dadosColaboradorPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public rubi_Syncbr_com_arauco_rh_dadosColaboradorClient(EndpointConfiguration endpointConfiguration) : 
                base(rubi_Syncbr_com_arauco_rh_dadosColaboradorClient.GetBindingForEndpoint(endpointConfiguration), rubi_Syncbr_com_arauco_rh_dadosColaboradorClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public rubi_Syncbr_com_arauco_rh_dadosColaboradorClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(rubi_Syncbr_com_arauco_rh_dadosColaboradorClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public rubi_Syncbr_com_arauco_rh_dadosColaboradorClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(rubi_Syncbr_com_arauco_rh_dadosColaboradorClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public rubi_Syncbr_com_arauco_rh_dadosColaboradorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<WsSenior.dadosColaboradorgetdadoscolaboradorOut> get_dados_colaboradorAsync(string user, string password, int encryption, WsSenior.dadosColaboradorgetdadoscolaboradorIn parameters)
        {
            return base.Channel.get_dados_colaboradorAsync(user, password, encryption, parameters);
        }
        
        public System.Threading.Tasks.Task<WsSenior.dadosColaboradorgetdadoscolaboradorBKPOut> get_dados_colaborador_BKPAsync(string user, string password, int encryption, WsSenior.dadosColaboradorgetdadoscolaboradorBKPIn parameters)
        {
            return base.Channel.get_dados_colaborador_BKPAsync(user, password, encryption, parameters);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.rubi_Syncbr_com_arauco_rh_dadosColaboradorPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.rubi_Syncbr_com_arauco_rh_dadosColaboradorPort))
            {
                return new System.ServiceModel.EndpointAddress("https://web12.senior.com.br:42200/g5-senior-services/rubi_Syncbr_com_arauco_rh_da" +
                        "dosColaborador");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return rubi_Syncbr_com_arauco_rh_dadosColaboradorClient.GetBindingForEndpoint(EndpointConfiguration.rubi_Syncbr_com_arauco_rh_dadosColaboradorPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return rubi_Syncbr_com_arauco_rh_dadosColaboradorClient.GetEndpointAddress(EndpointConfiguration.rubi_Syncbr_com_arauco_rh_dadosColaboradorPort);
        }
        
        public enum EndpointConfiguration
        {
            
            rubi_Syncbr_com_arauco_rh_dadosColaboradorPort,
        }
    }
}
