<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Arauco.Otimizador.Aws.Shared\Arauco.Otimizador.Aws.Shared.csproj" />
    <ProjectReference Include="..\Arauco.Otimizador.Common.Domain\Arauco.Otimizador.Common.Domain.csproj" />
    <ProjectReference Include="..\Arauco.Otimizador.Common.Email\Arauco.Otimizador.Common.Email.csproj" />
    <ProjectReference Include="..\Arauco.Otimizador.Data.Entities\Arauco.Otimizador.Data.Entities.csproj" />
    <ProjectReference Include="..\Arauco.Otimizador.Service.Base\Arauco.Otimizador.Service.Base.csproj" />
    <ProjectReference Include="..\Techer.Aws.Cognito\Techer.Aws.Cognito.csproj" />
    <ProjectReference Include="..\Techer.Common.Id\Techer.Common.Id.csproj" />
  </ItemGroup>

</Project>
