AWSTemplateFormatVersion: 2010-09-09
Description: >-
  arauco-otimizador-odata-api

Transform:
- AWS::Serverless-2016-10-31

Parameters:
  ENV:
    Description: Required. Environment dev/test/prod
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - test
      - prod
  APIDOMAIN:
    Description: Required. Domain name for API
    Type: String
    
Mappings:
  dev:
    values:
      AspNetEnv: Development
      SecurityGroupIds:
          - sg-0cfd5e09e65613b01
      SubnetIds:
          - subnet-04fc6c507f6eee036
          - subnet-09c191ff0ece61a4e
          - subnet-06b4822ebf0038c3a
  test:
    values:
      AspNetEnv: Testing
      SecurityGroupIds:
          - sg-08980c18bfd844362
      SubnetIds:
          - subnet-0055db092a2077262
          - subnet-07da12cebc36beff5
          - subnet-0c10474e6284efa04
  prod:
    values:
      AspNetEnv: Production
      SecurityGroupIds:
          - sg-0bbc4b7d39eea047d
      SubnetIds:
          - subnet-028c236579509043f
          - subnet-0a74405871a88df12
          - subnet-000095cb819756971

Globals:
  Function:
    VpcConfig:
      SecurityGroupIds: !FindInMap [ !Ref ENV, values, SecurityGroupIds ]
      SubnetIds: !FindInMap [ !Ref ENV, values, SubnetIds ]
    Environment:
      Variables:
        ASPNETCORE_ENVIRONMENT: !FindInMap [ !Ref ENV, values, AspNetEnv ]

  Api:
    EndpointConfiguration: REGIONAL
    Cors:
      AllowHeaders: "'Content-Type,x-workspace,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      AllowMethods: "'DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT'"
      AllowOrigin: "'*'"

Resources:
  HubDataApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: otimizador-data-api
      StageName: Staging

  HubDataApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: otimizador-data-api
      Description: Otimizador Data API
      Handler: Arauco.Otimizador.DataApi::Arauco.Otimizador.DataApi.LambdaEntryPoint::FunctionHandlerAsync
      MemorySize: 1024
      Timeout: 60
      Runtime: dotnet10
      Events:
        CartaoApiProxy:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId: !Ref HubDataApi
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy: 
            SecretArn: arn:aws:secretsmanager:sa-east-1:*:secret:*
        - DynamoDBCrudPolicy:
            TableName: OtimizadorKeyValue
        - DynamoDBCrudPolicy:
            TableName: KeyValue
        - DynamoDBCrudPolicy:
            TableName: OtimizadorLog

  UrlMapping:
    Type: AWS::ApiGateway::BasePathMapping
    DependsOn: 
      - HubDataApi
      - HubDataApiFunction
    Properties:
      BasePath: integration
      DomainName: !Ref APIDOMAIN
      RestApiId: !Ref HubDataApi
      Stage: !Ref HubDataApi.Stage
